const translations = {
    en: {
        // Nav & Global
        lang_name: "English",
        nav_home: "Home",
        nav_policy: "Leave Policy",
        nav_manual: "Employee Manual",
        nav_calc: "Leave Calculator",
        nav_salary_cer: "Request Salary Cerficate",
        nav_recommend_report: "Feedback&Complaints",
        footer_text: "© Wuerth Thailand. Internal Use Only.",
        
        // Home Section
        home_title: "Employee Service",
        home_subtitle: "Welcome to the employee information and benefits system",
        contact_title: "Contact Channels",
        btn_change_pass: "Change Admin Password",
        btn_edit_contact: "Edit Contact",
        contact_desc: "If you have any questions or encounter any problems, you can contact us directly.",
        btn_save: "Save",
        announcement_title: "HR Announcements",
        announcement_topic_label: "Topic:",
        announcement_body_label: "Content:",
        
        // Policy Section
        policy_sub: "Company Leave Policies and Regulations",
        vac_title: "Annual Vacation Leave",
        vac_cond: "General Conditions",
        vac_cond_1: "<span class='font-semibold text-gray-900'>New Employee:</span> Pro-rated after passing probation",
        vac_cond_2: "<span class='font-semibold text-gray-900'>Probation Period:</span> Can only be used in <span class='underline text-red-800'>Emergency</span> cases",
        vac_cond_3: "<span class='font-semibold text-gray-900'>Leave Carry Forward:</span> Max 5 days (must be used within the first 4 months of the next year)",
        vac_table_title: "Leave Entitlement Table",
        vac_yr_1: "Service < 2 years",
        vac_yr_2: "Service 2 - < 5 years",
        vac_yr_3: "Service \u2265 5 years / Mgmt",
        vac_day_14: "14 Days",
        vac_day_17: "17 Days",
        vac_day_19: "19 Days",
        vac_rule_title: "Leave Request Rules",
        vac_rule_1: "<span class='font-semibold text-gray-900'>Leave < 5 days:</span> Submit at least 5 days in advance",
        vac_rule_2: "<span class='font-semibold text-gray-900'>Leave \u2265 5 days:</span> Submit 2 weeks in advance",
        vac_rule_3: "<span class='font-semibold text-gray-900'>Emergency Leave:</span> 3 days/year (Notify before 10:00 AM)",
        
        sick_title: "Sick & Medical Leave",
        sick_day_text: "Days / Year<br/>Paid",
        sick_rule_1: "Sick leave for <span class='font-bold text-gray-900'>\u2265 3 consecutive days</span> requires a medical certificate",
        sick_rule_2: "In case of Hospital Admission, notify your manager and submit a medical certificate",
        sick_rule_3: "Notify your manager or HR before <span class='font-bold text-gray-900'>10:00 AM</span> on the day of leave",
        sick_warn_title: "Caution",
        sick_warn_text: "Improper use of leave rights or exceeding entitlements may result in deduction of leave days or being considered as Leave without pay for those days.",
        
        spec_title: "Special & Family Leave",
        spec_mat: "Maternity Leave",
        spec_mat_1: "• Max <strong>98 days</strong>",
        spec_mat_2: "• Paid for 45 days",
        spec_mat_3: "• Request 4 weeks prior",
        spec_mar: "Marriage Leave",
        spec_mar_1: "• <strong>3 days</strong> entitlement",
        spec_mar_2: "• Service \u2265 1 year",
        spec_mar_3: "• Attach marriage cert.",
        spec_pat: "Paternity Leave",
        spec_pat_1: "• <strong>5 days/child</strong>",
        spec_pat_2: "• Max 3 children",
        spec_pat_3: "• Attach birth cert.",
        spec_fun: "Funeral Leave",
        spec_fun_1: "• <strong>3 days</strong> entitlement",
        spec_fun_2: "• 10,000 THB assistance",
        spec_fun_3: "• Parents, Spouse, Child",
        
        oth_title: "Other Leaves",
        oth_edu_title: "Self-Development & Exams",
        oth_edu_1: "Must provide exam registration evidence",
        oth_edu_2: "6 days/year",
        oth_ster_title: "Sterilization Leave",
        oth_ster_1: "As specified in medical certificate",
        oth_ster_2: "Max 5 days",
        oth_mil_title: "Military Service Leave",
        oth_mil_1: "Call-up for military training",
        oth_mil_2: "60 days",
        oth_monk_title: "Monkhood Leave",
        oth_monk_1: "Subject to service years and company rules",
        oth_monk_2: "By Law",
        oth_warn_1: "Exceeding or improperly using leave rights will result in deduction of annual vacation or Leave without Pay.",
        oth_warn_2: "All types of leave must be <span class='font-bold underline'>approved by the supervisor and senior management</span>.",

        // Manual Section (Main Titles)
        manual_sub: "Wuerth (Thailand) Co., Ltd. (Version 3.3 Brief)",
        ch1_title: "Employment Contract",
        ch2_title: "Working Hours",
        ch3_title: "Termination of Employment",
        ch4_title: "Medical Benefits",
        ch5_title: "Special Allowances",
        ch6_title: "Salary Administration",
        ch7_title: "Business Ethics",
        ch8_title: "Rules and Regulations",
        ch9_title: "Grievance Procedure",

        // Chapter Section
        chapter1_title: "Chapter 1",
        chapter2_title: "Chapter 2",
        chapter3_title: "Chapter 3",
        chapter4_title: "Chapter 4",
        chapter5_title: "Chapter 5",
        chapter6_title: "Chapter 6",
        chapter7_title: "Chapter 7",
        chapter8_title: "Chapter 8",
        chapter9_title: "Chapter 9",

        // --- Manual Content Detail Translations ---
        // Chapter 1
        mn_ch1_sec1_title: "Job Classification and Grading",
        mn_ch1_table_h1: "Group",
        mn_ch1_table_h2: "Level",
        mn_ch1_table_h3: "Position",
        mn_ch1_note: "* Note: Positions 3 and 6 are the lowest, and 1 is the highest in each group.",
        mn_ch1_sec2_title: "Transfer and Relocation",
        mn_ch1_sec2_desc: "The Company has <u>absolute discretion</u> to transfer and assign employees to work in other departments or regional offices based on business needs as follows:",
        mn_ch1_sec2_l1: "Service or expertise required at the receiving unit",
        mn_ch1_sec2_l2: "Employee has been in the same position for a long time",
        mn_ch1_sec2_l3: "Reassignment of employees",
        mn_ch1_sec2_l4: "Company restructuring",
        mn_ch1_sec3_title: "Probationary Period",
        mn_ch1_sec3_l1: "<strong>Duration:</strong> Maximum 119 days for all types of employment",
        mn_ch1_sec3_l2: "<strong>Evaluation:</strong> At least 1 evaluation during probation with department head and MD",
        mn_ch1_sec3_l3: "<strong>Confirmation:</strong> Company will notify in writing. If failed, 1 payment cycle advance notice is given",
        mn_ch1_sec3_l4: "<strong>Termination:</strong> Company reserves the right to terminate immediately for job abandonment or inappropriate behavior",

        // Chapter 2
        mn_ch2_sec1_title: "2.1 Normal Working Hours",
        mn_ch2_table_h1: "Location / Dept",
        mn_ch2_table_h2: "Work Days",
        mn_ch2_table_h3: "Work Hours",
        mn_ch2_table_h4: "Break Time",
        mn_ch2_loc1: "Office",
        mn_ch2_loc2: "Warehouse",
        mn_ch2_loc3: "Sales",
        mn_ch2_day1: "Mon - Fri",
        mn_ch2_day2: "Mon - Fri (Sat per calendar)",
        mn_ch2_note1: "* Weekly working hours: 40 hours (8 hours/day) (Sales max 48 hours)",
        mn_ch2_sec2_title: "Additional Conditions",
        mn_ch2_wfh_title: "Work from Home",
        mn_ch2_wfh_desc: "WFH policy 1 day/week (Requires approval) <u>Except</u> Warehouse, Master Service, and Sales",
        mn_ch2_neg_title: "Negative Working Hours",
        mn_ch2_neg_desc: "If working hours are negative at month-end, at least 0.5 days of annual leave will be deducted. If leave is exhausted, disciplinary action applies.",

        // Chapter 3
        mn_ch3_sec1_title: "3.1 Termination of Employment",
        mn_ch3_sec1_desc: "Parties must provide written notice <strong>1 payment cycle</strong> (1 month) in advance or pay in lieu of notice.",
        mn_ch3_sec1_l1: "Probation: 1 month notice",
        mn_ch3_sec1_l2: "Permanent: 1 month notice",
        mn_ch3_sec1_note: "* The Company reserves the right to terminate immediately for poor performance, disciplinary breach, or dangerous behavior.",
        mn_ch3_sec2_title: "3.2 Termination Procedures",
        mn_ch3_sec2_l1: "Return all company property",
        mn_ch3_sec2_l2: "Settle all outstanding debts",
        mn_ch3_sec2_l3: "Right to receive payment for unused annual leave (if procedures are fully followed)",
        mn_ch3_sec3_title: "3.3 Job Abandonment",
        mn_ch3_sec3_desc: "Absence without notice or valid reason for <strong>3 consecutive working days</strong> is considered job abandonment, leading to immediate termination and possible wage deduction.",
        mn_ch3_sec4_title: "3.4 Retirement",
        mn_ch3_sec4_desc: "Official retirement on the <strong>60th birthday anniversary</strong> (ends on the last day of the birth month).",
        mn_ch3_sec4_note: "* The Company may offer continued employment at its discretion.",
        mn_ch3_sec5_title: "3.5 Exit Interview",
        mn_ch3_sec5_desc: "Employees may be required to attend an interview with the <strong>Department Head</strong> or <strong>Senior Management</strong> upon termination.",

        // Chapter 4
        mn_ch4_sec1_title: "4.1 Life and Health Insurance (Group Insurance)",
        mn_ch4_sec1_l1: "Effective after <strong>passing probation</strong>",
        mn_ch4_sec1_l2: "OPD/IPD limits depend on the company's insurance plan",
        mn_ch4_sec1_l3: "Includes annual health check-up benefits",
        mn_ch4_table_h1: "Benefit",
        mn_ch4_table_h2: "Limit / Details",
        mn_ch4_den: "Dental",
        mn_ch4_den_desc: "<span class='font-semibold'>Total 4,000 THB/year</span>",
        mn_ch4_opt: "Optical",
        mn_ch4_opt_desc: "<span class='font-semibold'>Max 4,000 THB/year</span> (Lenses only - excludes frames)",

        // Chapter 5
        mn_ch5_sec1_title: "5.1 Domestic Travel Expenses",
        mn_ch5_table1_h1: "Employee Type",
        mn_ch5_table1_h2: "Vehicle",
        mn_ch5_table1_h3: "Rate (THB/km)",
        mn_ch5_emp1: "Internal Staff",
        mn_ch5_emp2: "Sales Staff",
        mn_ch5_veh1: "Car",
        mn_ch5_veh2: "Motorcycle",
        mn_ch5_rate1: "3 (Requires approval or Fleet Card)",
        mn_ch5_sec1_l1: "<strong>Conditions:</strong> Company supports travel expenses for employees traveling for business purposes only.",
        mn_ch5_sec1_l2: "<strong>EV Cars:</strong> Reimbursed at actual charging cost (receipt required).",
        mn_ch5_sec1_l3: "<strong>Toll/Parking:</strong> Actual cost (receipt required).",
        mn_ch5_sec2_title: "5.2 Mobile Phone and Electronic Device Policy",
        mn_ch5_sec2_l1: "<strong>Usage Rights:</strong> The Company will provide devices (mobile, laptop, iPad) and phone numbers as appropriate for the position, at management's discretion.",
        mn_ch5_sec2_l2: "<strong>Ownership and Purpose:</strong> All devices, phone numbers, and accounts (Apple ID, LINE, etc.) are <strong>Company Property</strong> and must be used for business purposes only.",
        mn_ch5_sec2_l3: "<strong>Account Management Prohibitions:</strong> Do not change settings (password/email), delete customer data or chat history, or transfer access rights.",
        mn_ch5_sec2_l4: "<strong>Disciplinary Action:</strong> Unauthorized modification or deletion of data is a serious disciplinary offense, which may lead to disciplinary action or termination.",
        mn_ch5_sec3_1_title: "5.3.1 Travel Class and Reimbursement Rights",
        mn_ch5_table2_h1: "Item",
        mn_ch5_table2_h2: "Reimbursement Right",
        mn_ch5_t2_r1_c1: "Internal Staff <br><span class='text-xs font-normal text-gray-500'>(Without Fleet Card)</span>",
        mn_ch5_t2_r1_c2: "Car: 8 THB/km<br>Motorcycle: 5 THB/km",
        mn_ch5_t2_r2_c1: "Sales Staff",
        mn_ch5_t2_r2_c2: "Prior approval from Sales Director only",
        mn_ch5_t2_taxi: "Taxi",
        mn_ch5_t2_taxi_r: "As per receipt",
        mn_ch5_t2_flight: "Flights",
        mn_ch5_t2_flight_r: "Economy class",
        mn_ch5_t2_tax: "Airport Tax",
        mn_ch5_t2_tax_r: "As per receipt",
        mn_ch5_t2_toll: "Toll and Parking",
        mn_ch5_t2_toll_r: "As per receipt",
        mn_ch5_sec3_2_title: "5.3.2 Per Diem",
        mn_ch5_sec3_2_l1: "Domestic: <strong>270 THB/day</strong> (Internal staff only)",
        mn_ch5_sec3_2_l2: "Overseas: <strong>500 THB/day</strong> (Snacks/Drinks) + Actual meals (Max 3,100)",
        mn_ch5_sec3_3_title: "5.3.3 Accommodation",
        mn_ch5_sec3_3_l1: "Domestic: <strong>550 THB/night</strong> (or partner hotels)",
        mn_ch5_sec3_3_l2: "Overseas: Depending on the city (booked via admin)",
        mn_ch5_sec3_3_l3: "Male and female employees cannot share the same room",
        mn_ch5_sec4_title: "5.4 Conditions for Expense Reimbursement",
        mn_ch5_sec4_l1: "Travel expenses must be submitted by the following month at the latest.",
        mn_ch5_sec4_l2: "Submit request with original receipts to Accounting <strong>before the 22nd of the month</strong>.",
        mn_ch5_sec4_l3: "Late submissions will be processed in the next billing cycle.",
        mn_ch5_sec4_l4: "The Company reserves the right to reject payments without original documents.",
        mn_ch5_sec5_title: "5.5 Training and Development",
        mn_ch5_sec5_l1: "Training entitlement max <strong>40 hours/year</strong> (internal/external combined)",
        mn_ch5_sec5_l2: "Employees who resigned/under investigation are not eligible.",
        mn_ch5_sec5_l3: "May require signing a <strong>Guarantor Agreement</strong> for company-selected training.",
        mn_ch5_sec5_l4: "Must submit training evaluation form to HR within 2 working days after completion.",

        // Chapter 6
        mn_ch6_sec1_title: "6.1 Salary Payment",
        mn_ch6_sec1_desc: "Paid on the <strong>last Friday of the month</strong> (or last working day if it falls on a holiday).",
        mn_ch6_sec2_title: "6.2 Provident Fund (EPF)",
        mn_ch6_table1_h1: "Tenure",
        mn_ch6_table1_h2: "Contribution (Company)",
        mn_ch6_table1_h3: "Accumulation (Employee)",
        mn_ch6_t1_1: "&lt; 2 Years",
        mn_ch6_t1_2: "2 - &lt; 5 Years",
        mn_ch6_t1_3: "&ge; 5 Years",
        mn_ch6_t1_c1: "Up to 8%",
        mn_ch6_t1_c2: "Up to 10%",
        mn_ch6_sec5_title: "6.5 Salary Increase and Bonus",
        mn_ch6_sec5_desc: "Based on <strong>Company's discretion</strong> and annual performance, considering:",
        mn_ch6_sec5_l1: "Performance improvement",
        mn_ch6_sec5_l2: "Reliability and attitude",
        mn_ch6_sec5_l3: "Cooperation and disciplinary compliance",
        mn_ch6_sec5_l4: "Annual performance appraisal",
        mn_ch6_sec5_note: "* Not a legal entitlement guaranteed every year.",
        mn_ch6_sec6_title: "6.6 Overtime (OT)",
        mn_ch6_table2_h1: "Work Type",
        mn_ch6_table2_h2: "Compensation Rate (Hourly)",
        mn_ch6_t2_r1_c1: "Overtime on regular workdays",
        mn_ch6_t2_r1_c2: "<span class='font-bold text-red-600'>1.5 times</span>",
        mn_ch6_t2_r2_c1: "Work on holidays (normal hours)",
        mn_ch6_t2_r2_c2: "<span class='font-bold text-red-600'>1-2 times</span>",
        mn_ch6_t2_r3_c1: "Overtime on holidays",
        mn_ch6_t2_r3_c2: "<span class='font-bold text-red-600'>3 times</span>",
        mn_ch6_exc_title: "Exceptions (Not counted as OT)",
        mn_ch6_exc_l1: "Break times",
        mn_ch6_exc_l2: "Sick leave / Annual leave and other absences",
        mn_ch6_exc_l3: "Attending training on holidays",
        mn_ch6_proc_title: "Reimbursement Process",
        mn_ch6_proc_l1: "<u>Must be approved by supervisor before working</u>",
        mn_ch6_proc_l2: "Submit form by the <strong>20th of the month</strong>",

        // Chapter 7
        mn_ch7_sec1_title: "Integrity",
        mn_ch7_sec1_l1: "Comply with laws and highest ethical standards",
        mn_ch7_sec1_l2: "Do not disclose confidential company/customer information",
        mn_ch7_sec1_l3: "Do not use pirated software",
        mn_ch7_sec1_l4: "Must respect the privacy of other users at all times (files, disks, emails, data, etc.)",
        mn_ch7_sec2_title: "Personal Behavior and Ethics",
        mn_ch7_sec2_l1: "Do not engage in businesses competing with the company",
        mn_ch7_sec2_l2: "Do not accept high-value gifts or bribes",
        mn_ch7_sec2_l3: "Do not borrow money from customers or partners",
        mn_ch7_sec2_l4: "Do not use the company's name or relationship to endorse/promote other organizations",
        mn_ch7_sec2_l5: "Do not introduce obscene or threatening material into public-accessible spaces",
        mn_ch7_sec2_l6: "Must honestly and fully obey, comply with, and respect the laws, etc.",
        mn_ch7_it_pol: "<strong>IT Policy:</strong> Do not use company computers for personal business, hacking, or violating others' privacy.",
        mn_ch7_note: "<strong>Note:</strong> \"The above content is only a summary of the basic prohibitions and work ethics. Employees must study and strictly follow the full company policy to maintain organizational standards.\"",

        // Chapter 8
        mn_ch8_sec1_title: "Disciplinary Penalties",
        mn_ch8_sec1_1: "1. Verbal Warning",
        mn_ch8_sec1_2: "2. Written Warning",
        mn_ch8_sec1_3: "3. Suspension (Without Pay)",
        mn_ch8_sec1_4: "4. Termination",
        mn_ch8_sec2_title: "Serious Offenses (Immediate Termination/No Severance)",
        mn_ch8_sec2_l1: "Fraud / Embezzlement / Falsifying sales",
        mn_ch8_sec2_l2: "Job abandonment for 3 consecutive days",
        mn_ch8_sec2_l3: "Drug use / Drinking alcohol at work / Theft",
        mn_ch8_sec2_l4: "Disclosing company secrets / Forging documents",
        mn_ch8_sec2_l5: "Bullying / Harassment / Discrimination",
        mn_ch8_sec3_title: "General Offenses (Warning)",
        mn_ch8_sec3_l1: "Lateness / Absence without leave",
        mn_ch8_sec3_l2: "Using work time for personal matters",
        mn_ch8_sec3_l3: "Inappropriate attire",
        mn_ch8_sec3_l4: "Bringing outsiders to the office without permission",
        mn_ch8_sec4_title: "Severance Pay (By Law)",
        mn_ch8_table_h1: "Tenure",
        mn_ch8_table_h2: "Severance Pay",
        mn_ch8_t_1: "120 Days - 1 Year", mn_ch8_t_1_v: "30 Days",
        mn_ch8_t_2: "1 - 3 Years", mn_ch8_t_2_v: "90 Days",
        mn_ch8_t_3: "3 - 6 Years", mn_ch8_t_3_v: "180 Days",
        mn_ch8_t_4: "6 - 10 Years", mn_ch8_t_4_v: "240 Days",
        mn_ch8_t_5: "10 - 20 Years", mn_ch8_t_5_v: "300 Days",
        mn_ch8_t_6: "20 Years or more", mn_ch8_t_6_v: "400 Days",

        // Chapter 9
        mn_ch9_desc: "For employees who feel unfairly treated at work or have conflicts (excluding promotion requests or personal matters).",
        mn_ch9_step1_title: "Step 1: Discuss with Supervisor",
        mn_ch9_step1_desc: "Speak directly with your immediate supervisor or business unit head first to resolve the issue initially.",
        mn_ch9_step2_title: "Step 2: Submit to Management",
        mn_ch9_step2_desc: "If not resolved within <strong>3 working days</strong>, submit a formal letter to HR to request a meeting with senior management (COO/CEO/MD).",
        mn_ch9_step3_title: "Step 3: Decision",
        mn_ch9_step3_desc: "HR will schedule an appointment within 7 days, and management will notify the decision within <strong>3 working days</strong> after the meeting (decision is final).",
        
        // Calculator Section
        calc_sub: "Check your entitlement based on tenure and policy",
        calc_date_label: "Start Date",
        calc_today: "Today:",
        calc_tenure: "Tenure:",
        btn_calc: "Calculate Leave",
        calc_ph_title: "Please specify start date",
        calc_ph_desc: "The system will automatically calculate your leave entitlement.",
        calc_unit: "Days",
        calc_desc: "Your Annual Vacation Leave Entitlement",
        calc_detail_title: "Details",
        
        // Modals & Placeholders
        login_title: "Admin Console",
        placeholder_user: "Username",
        placeholder_pass: "Password",
        btn_login: "Login",
        new_post_title: "Add New Announcement",
        post_topic_label: "Topic",
        placeholder_topic: "Enter topic...",
        post_content_label: "Content",
        btn_post: "Post Announcement",
        change_pass_title: "Change Admin Password",
        new_user_label: "New Username:",
        new_pass_label: "New Password:",
        btn_save_pass: "Save New Password",
        
        // Dynamic JS Strings
        pin_badge: "Pinned",
        hidden_admin: "Hidden (Admin only)",
        pin: "Pin",
        unpin: "Unpin",
        edit: "Edit",
        show: "Show",
        hide: "Hide",
        delete: "Delete",
        btn_saving: "Saving...",
        btn_save_edit: "Save Changes",
        alert_no_topic: "Please enter a topic",
        confirm_delete: "Are you sure you want to delete this announcement?",
        alert_error: "Error: ",
        alert_fill_all: "Please fill in all fields",
        btn_checking: "Checking...",
        alert_login_fail: "Invalid Username or Password",
        confirm_pass: "Are you sure you want to change the admin password?",
        alert_pass_success: "Password changed successfully!",
        calc_invalid_date_badge: "Invalid Date",
        calc_invalid_date_msg: "<span class='text-red-600 font-bold'>Cannot select a future date</span><br>Please select your start date again",
        calc_probation_badge: "Probation Period",
        calc_probation_msg: "Your tenure is {days} days <br> According to company policy, employees are entitled to annual leave only after passing probation (119 days).",
        calc_prorate_badge: "Less than 1 year (Pro-rate)",
        calc_prorate_msg: "Probation passed ({days} days) <br> Entitled to pro-rated leave based on 14 days <br><br> Formula: ({days} / 365) × 14 = {raw} days",
        calc_1_2_badge: "1 - < 2 Years",
        calc_1_2_msg: "You are entitled to 14 days of annual leave as you have reached 1 year of service.",
        calc_2_5_badge: "2 - < 5 Years",
        calc_2_5_msg: "You are entitled to 17 days of annual leave based on your service years.",
        calc_5_up_badge: "5 Years and above",
        calc_5_up_msg: "You are entitled to the maximum of 19 days of annual leave based on your service years."
    },
    th: {
        // Nav & Global
        lang_name: "ไทย",
        nav_home: "หน้าหลัก",
        nav_policy: "สิทธิการลา",
        nav_manual: "คู่มือพนักงาน",
        nav_calc: "คำนวณสิทธิวันลา",
        nav_salary_cer: "ขอใบรับรองเงินเดือน",
        nav_recommend_report: "ข้อเสนอแนะ&ร้องเรียน",
        footer_text: "© Wuerth Thailand. Internal Use Only.",
        
        // Home Section
        home_title: "Employee Service",
        home_subtitle: "ยินดีต้อนรับสู่ระบบบริการข้อมูลพนักงานและสวัสดิการ",
        contact_title: "ช่องทางการติดต่อ",
        btn_change_pass: "เปลี่ยนรหัสแอดมิน",
        btn_edit_contact: "แก้ไขการติดต่อ",
        contact_desc: "หากมีข้อสงสัย คำถามเพิ่มเติม หรือพบปัญหาใด ๆ สามารถติดต่อสอบถามได้โดยตรง",
        btn_save: "บันทึก",
        announcement_title: "ประกาศจากฝ่ายบุคคล",
        announcement_topic_label: "หัวข้อประกาศ:",
        announcement_body_label: "เนื้อหา:",
        
        // Policy Section
        policy_sub: "ระเบียบการลาประเภทต่างๆ ของบริษัท",
        vac_title: "สิทธิวันหยุดพักผ่อนประจำปี",
        vac_cond: "เงื่อนไขทั่วไป",
        vac_cond_1: "<span class='font-semibold text-gray-900'>พนักงานใหม่:</span> ได้สิทธิแบบเฉลี่ย (Pro-rate) หลังผ่านทดลองงาน",
        vac_cond_2: "<span class='font-semibold text-gray-900'>ช่วงทดลองงาน:</span> ใช้สิทธิได้เฉพาะกรณี <span class='underline text-red-800'>ฉุกเฉิน</span> เท่านั้น",
        vac_cond_3: "<span class='font-semibold text-gray-900'>โอนวันลา:</span> ได้สูงสุด 5 วัน (ใช้ภายใน 4 เดือนแรกของปีถัดไป)",
        vac_table_title: "ตารางสิทธิวันลา",
        vac_yr_1: "อายุงาน < 2 ปี",
        vac_yr_2: "อายุงาน 2 - < 5 ปี",
        vac_yr_3: "อายุงาน \u2265 5 ปี / บริหาร",
        vac_day_14: "14 วัน",
        vac_day_17: "17 วัน",
        vac_day_19: "19 วัน",
        vac_rule_title: "ระเบียบการยื่นใบลา",
        vac_rule_1: "<span class='font-semibold text-gray-900'>ลา < 5 วัน:</span> ยื่นล่วงหน้าอย่างน้อย 5 วัน",
        vac_rule_2: "<span class='font-semibold text-gray-900'>ลา \u2265 5 วัน:</span> ยื่นล่วงหน้า 2 สัปดาห์",
        vac_rule_3: "<span class='font-semibold text-gray-900'>ลากิจฉุกเฉิน:</span> 3 วัน/ปี (แจ้งก่อน 10.00 น.)",
        
        sick_title: "วันลาป่วย & รักษาพยาบาล",
        sick_day_text: "วัน / ปี<br/>ที่ได้รับ<br/>ค่าจ้างปกติ",
        sick_rule_1: "ลาป่วยติดต่อกัน <span class='font-bold text-gray-900'>\u2265 3 วัน</span> ต้องแนบใบรับรองแพทย์",
        sick_rule_2: "กรณี Admit รพ. ต้องแจ้งหัวหน้าและส่งใบรับรองแพทย์",
        sick_rule_3: "แจ้งหัวหน้า หรือ HR ก่อนเวลา <span class='font-bold text-gray-900'>10.00 น.</span> ของวันที่ลา",
        sick_warn_title: "ข้อควรระวัง",
        sick_warn_text: "การใช้สิทธิผิดวิธีหรือเกินสิทธิ วันลาอาจถูกหัก หรือพิจารณาเป็นการลาโดยไม่ได้รับค่าจ้าง (Leave without pay) ในวันที่ลานั้นๆ",
        
        spec_title: "วันลาพิเศษ & ครอบครัว",
        spec_mat: "ลาคลอด (หญิง)",
        spec_mat_1: "• สูงสุด <strong>98 วัน</strong>",
        spec_mat_2: "• รับค่าจ้าง 45 วัน",
        spec_mat_3: "• ยื่นขอ 4 สัปดาห์ก่อนลา",
        spec_mar: "ลาแต่งงาน",
        spec_mar_1: "• ได้ <strong>3 วัน</strong>",
        spec_mar_2: "• อายุงาน \u2265 1 ปี",
        spec_mar_3: "• แนบใบสำคัญการสมรส",
        spec_pat: "ลาดูแลบุตร (ชาย)",
        spec_pat_1: "• ได้ <strong>5 วัน/บุตร</strong>",
        spec_pat_2: "• สูงสุด 3 คน",
        spec_pat_3: "• ต้องแนบสูติบัตร",
        spec_fun: "งานศพ",
        spec_fun_1: "• ได้ <strong>3 วัน</strong>",
        spec_fun_2: "• เงินช่วย 10,000 บาท",
        spec_fun_3: "• พ่อ, แม่, คู่สมรส, บุตร",
        
        oth_title: "การลาอื่นๆ",
        oth_edu_title: "การพัฒนาตนเอง & สุขภาพ",
        oth_edu_1: "ต้องมีหลักฐานการสมัครสอบ",
        oth_edu_2: "6 วัน/ปี",
        oth_ster_title: "ลาทำหมัน",
        oth_ster_1: "ตามระยะเวลาในใบรับรองแพทย์",
        oth_ster_2: "สูงสุด 5 วัน",
        oth_mil_title: "หน้าที่พลเมือง & ศาสนา",
        oth_mil_1: "เรียกพลเพื่อฝึกวิชาทหาร",
        oth_mil_2: "60 วัน",
        oth_monk_title: "ลาบวช",
        oth_monk_1: "ตามอายุงานและระเบียบบริษัท",
        oth_monk_2: "ตามกฎหมาย",
        oth_warn_1: "การใช้สิทธิเกิน หรือไม่ถูกต้อง จะถูกหักวันหยุดพักผ่อนหรือเป็นการลาไม่รับค่าจ้าง (Leave without Pay)",
        oth_warn_2: "การลาทุกประเภทต้องได้รับ <span class='font-bold underline'>อนุมัติจากหัวหน้างานและฝ่ายบริหารอาวุโส</span>",

        // Manual Section
        manual_sub: "บริษัท เวือร์ท (ประเทศไทย) จำกัด (เวอร์ชั่น 3.3 ฉบับย่อ)",
        ch1_title: "สัญญาจ้างแรงงาน",
        ch2_title: "ชั่วโมงทำงาน",
        ch3_title: "การออกจากการเป็นพนักงานบริษัท",
        ch4_title: "สวัสดิการรักษาพยาบาล",
        ch5_title: "ผลตอบแทนพิเศษ",
        ch6_title: "การบริหารจัดการเงินเดือน",
        ch7_title: "จริยธรรมทางธุรกิจ",
        ch8_title: "กฎระเบียบและข้อบังคับ",
        ch9_title: "กระบวนการร้องทุกข์",

        // Chapter Section
        chapter1_title: "บทที่ 1",
        chapter2_title: "บทที่ 2",
        chapter3_title: "บทที่ 3",
        chapter4_title: "บทที่ 4",
        chapter5_title: "บทที่ 5",
        chapter6_title: "บทที่ 6",
        chapter7_title: "บทที่ 7",
        chapter8_title: "บทที่ 8",
        chapter9_title: "บทที่ 9",

        // --- Manual Content Detail Translations ---
        // Chapter 1
        mn_ch1_sec1_title: "การจำแนกประเภทงานและการจัดลำดับ",
        mn_ch1_table_h1: "กลุ่ม",
        mn_ch1_table_h2: "ระดับ",
        mn_ch1_table_h3: "ตำแหน่ง",
        mn_ch1_note: "* หมายเหตุ: ตำแหน่ง 3 และ 6 อยู่ต่ำที่สุด และ 1 อยู่สูงที่สุดของแต่ละกลุ่ม",
        mn_ch1_sec2_title: "การโอนย้ายและการไปปฏิบัติงานที่หน่วยงานอื่น",
        mn_ch1_sec2_desc: "บริษัทมี<u>ดุลพินิจเด็ดขาด</u>ในการโอนย้ายและส่งพนักงานไปปฏิบัติงานในส่วนแผนกหรือสํานักงานภูมิภาคของบริษัท ตามความต้องการทางธุรกิจ ดังต่อไปนี้",
        mn_ch1_sec2_l1: "บริการหรือความเชี่ยวชาญที่หน่วยงานที่รับการโอนย้าย",
        mn_ch1_sec2_l2: "พนักงานปฏิบัติงานในตําแหน่งเดียวกันมาเป็นเวลานาน",
        mn_ch1_sec2_l3: "การจัดตําแหน่งใหม่ให้กับพนักงาน",
        mn_ch1_sec2_l4: "การปรับโครงสร้างบริษัท",
        mn_ch1_sec3_title: "การทดลองงาน",
        mn_ch1_sec3_l1: "<strong>ระยะเวลา:</strong> สูงสุด 119 วัน สำหรับการจ้างงานทุกประเภท",
        mn_ch1_sec3_l2: "<strong>การประเมิน:</strong> ต้องมีการประเมินอย่างน้อย 1 ครั้งระหว่างทดลองงาน กับหัวหน้าแผนกและกรรมการผู้จัดการ",
        mn_ch1_sec3_l3: "<strong>การบรรจุ:</strong> บริษัทจะแจ้งเป็นหนังสือ หากไม่ผ่านจะมีการแจ้งล่วงหน้า (1 รอบการจ่ายค่าจ้าง)",
        mn_ch1_sec3_l4: "<strong>การยกเลิกสัญญา:</strong> บริษัทสงวนสิทธิ์เลิกจ้างทันทีหากละทิ้งงาน หรือมีพฤติกรรมไม่เหมาะสม",

        // Chapter 2
        mn_ch2_sec1_title: "2.1 เวลาทำงานปกติ",
        mn_ch2_table_h1: "สถานที่ / ฝ่าย",
        mn_ch2_table_h2: "วันทำงาน",
        mn_ch2_table_h3: "เวลาทำงาน",
        mn_ch2_table_h4: "เวลาพัก",
        mn_ch2_loc1: "สำนักงาน",
        mn_ch2_loc2: "คลังสินค้า",
        mn_ch2_loc3: "ฝ่ายขาย",
        mn_ch2_day1: "จันทร์ - ศุกร์",
        mn_ch2_day2: "จันทร์ - ศุกร์ (เสาร์ตามปฏิทิน)",
        mn_ch2_note1: "* ชั่วโมงทำงานรายสัปดาห์ 40 ชั่วโมง (8 ชัวโมงต่อวัน) (ฝ่ายขายไม่เกิน 48 ชั่วโมง)",
        mn_ch2_sec2_title: "เงื่อนไขเพิ่มเติม",
        mn_ch2_wfh_title: "Work from Home",
        mn_ch2_wfh_desc: "นโยบายทำงานที่บ้าน 1 วัน/สัปดาห์ (ต้องได้รับอนุมัติ) <u>ยกเว้น</u> แผนกคลังสินค้า, มาสเตอร์เซอร์วิส และฝ่ายขาย",
        mn_ch2_neg_title: "เวลาทำงานติดลบ",
        mn_ch2_neg_desc: "สิ้นเดือนหากชั่วโมงทำงานติดลบ จะถูกหักวันลาพักร้อนอย่างน้อย 0.5 วัน หากวันลาหมดจะมีผลทางวินัย",

        // Chapter 3
        mn_ch3_sec1_title: "3.1 การสิ้นสุดการจ้างงาน",
        mn_ch3_sec1_desc: "คู่สัญญาต้องบอกกล่าวล่วงหน้าเป็นหนังสือ <strong>1 รอบการจ่ายค่าจ้าง</strong> (1 เดือน) หรือจ่ายสินจ้างแทนการบอกกล่าว",
        mn_ch3_sec1_l1: "ช่วงทดลองงาน: บอกกล่าว 1 เดือน",
        mn_ch3_sec1_l2: "พนักงานบรรจุ: บอกกล่าว 1 เดือน",
        mn_ch3_sec1_note: "* บริษัทขอสงวนสิทธิ์เลิกจ้างทันทีหากปฏิบัติงานไม่มีคุณภาพ, ผิดวินัย, หรือมีพฤติกรรมที่เป็นอันตราย",
        mn_ch3_sec2_title: "3.2 ขั้นตอนการเลิกจ้าง",
        mn_ch3_sec2_l1: "คืนทรัพย์สินทั้งหมดของบริษัท",
        mn_ch3_sec2_l2: "ชำระหนี้สินคงค้างทั้งหมด",
        mn_ch3_sec2_l3: "สิทธิรับเงินค่าวันหยุดพักผ่อนที่ไม่ได้ใช้ (หากปฏิบัติตามขั้นตอนครบถ้วน)",
        mn_ch3_sec3_title: "3.3 การละทิ้งงาน",
        mn_ch3_sec3_desc: "การขาดงานโดยไม่แจ้งหรือไม่มีเหตุอันสมควรติดต่อกัน <strong>3 วันทำการ</strong> ถือว่าละทิ้งงาน อาจนำไปสู่การเลิกจ้างทันทีและอาจถูกหักค่าจ้าง",
        mn_ch3_sec4_title: "3.4 เกษียณอายุ",
        mn_ch3_sec4_desc: "เกษียณอายุอย่างเป็นทางการใน <strong>วันครบรอบวันเกิดปีที่ 60</strong> (สิ้นสุดวันสุดท้ายของเดือนเกิด)",
        mn_ch3_sec4_note: "* บริษัทอาจเสนอจ้างงานต่อได้ตามดุลพินิจ",
        mn_ch3_sec5_title: "3.5 การสัมภาษณ์พนักงานที่ออก",
        mn_ch3_sec5_desc: "พนักงานอาจต้องเข้ารับการสัมภาษณ์กับ <strong>หัวหน้าแผนก</strong> หรือ <strong>ฝ่ายบริหารอาวุโส</strong> เมื่อสิ้นสุดการจ้างงาน",

        // Chapter 4
        mn_ch4_sec1_title: "4.1 ประกันชีวิตและสุขภาพ (Group Insurance)",
        mn_ch4_sec1_l1: "มีผลบังคับใช้เมื่อ<strong>ผ่านการทดลองงาน</strong>แล้ว",
        mn_ch4_sec1_l2: "วงเงินคุ้มครอง OPD/IPD ขึ้นอยู่กับแผนประกันที่บริษัทจัดให้",
        mn_ch4_sec1_l3: "มีสวัสดิการตรวจสุขภาพประจำปี",
        mn_ch4_table_h1: "สวัสดิการ",
        mn_ch4_table_h2: "วงเงิน / รายละเอียด",
        mn_ch4_den: "ทันตกรรม",
        mn_ch4_den_desc: "<span class='font-semibold'>รวม 4,000 บาท/ปี</span>",
        mn_ch4_opt: "จักษุวิทยา",
        mn_ch4_opt_desc: "<span class='font-semibold'>สูงสุด 4,000 บาท/ปี</span> (เฉพาะเลนส์-ไม่รวมกรอบแว่น)",

        // Chapter 5
        mn_ch5_sec1_title: "5.1 การเบิกค่าใช้จ่ายในการเดินทาง (ในประเทศ)",
        mn_ch5_table1_h1: "ประเภทพนักงาน",
        mn_ch5_table1_h2: "ยานพาหนะ",
        mn_ch5_table1_h3: "อัตราเบิก (บาท/กม.)",
        mn_ch5_emp1: "พนักงานภายใน",
        mn_ch5_emp2: "พนักงานฝ่ายขาย",
        mn_ch5_veh1: "รถยนต์",
        mn_ch5_veh2: "รถจักรยานยนต์",
        mn_ch5_rate1: "3 (ต้องขออนุมัติ หรือใช้ Fleet Card)",
        mn_ch5_sec1_l1: "<strong>เงื่อนไข</strong> บริษัทสนับสนุนค่าใช้จ่ายในการเดินทางสําหรับพนักงานที่ต้องการเดินทางเพื่อวัตถุประสงค์ทางธุรกิจเท่านั้น",
        mn_ch5_sec1_l2: "<strong>รถยนต์ไฟฟ้า (EV):</strong> เบิกตามค่าชาร์จจริง (ต้องมีหลักฐาน)",
        mn_ch5_sec1_l3: "<strong>ทางด่วน/จอดรถ:</strong> เบิกตามจริง (ต้องมีใบเสร็จ)",
        mn_ch5_sec2_title: "5.2 นโยบายโทรศัพท์มือถือและอุปกรณ์อิเล็กทรอนิกส์",
        mn_ch5_sec2_l1: "<strong>สิทธิ์การใช้งานตามความจำเป็น:</strong> บริษัทจะจัดสรรอุปกรณ์ (มือถือ, แล็ปท็อป, ไอแพด) และเบอร์โทรศัพท์ให้ตามความเหมาะสมของตำแหน่งงาน โดยการพิจารณาของฝ่ายบริหาร",
        mn_ch5_sec2_l2: "<strong>กรรมสิทธิ์และวัตถุประสงค์:</strong> อุปกรณ์ เบอร์โทรศัพท์ และบัญชีใช้งานทั้งหมด (Apple ID, LINE ฯลฯ) ถือเป็น<strong>ทรัพย์สินของบริษัท</strong>ให้ใช้เพื่อวัตถุประสงค์ทางธุรกิจเท่านั้น",
        mn_ch5_sec2_l3: "<strong>ข้อห้ามในการจัดการบัญชี:</strong>ห้ามแก้ไขการตั้งค่า (รหัสผ่าน/อีเมล) ห้ามลบข้อมูลลูกค้าหรือประวัติการสนทนา และห้ามโอนสิทธิ์การเข้าถึงบัญชีโดยเด็ดขาด",
        mn_ch5_sec2_l4: "<strong>บทลงโทษทางวินัย:</strong> การแก้ไขหรือลบข้อมูลโดยไม่ได้รับอนุญาตถือเป็น ความผิดวินัยร้ายแรง ซึ่งอาจส่งผลให้ถูกดำเนินการทางวินัยหรือเลิกจ้างได้",
        mn_ch5_sec3_1_title: "5.3.1 ชั้นการเดินทางและสิทธิการเบิก",
        mn_ch5_table2_h1: "รายการ",
        mn_ch5_table2_h2: "สิทธิที่เบิกได้",
        mn_ch5_t2_r1_c1: "พนักงานภายใน <br><span class='text-xs font-normal text-gray-500'>(ที่ไม่ได้รับฟลีทการ์ด)</span>",
        mn_ch5_t2_r1_c2: "รถยนต์: 8 บาท/กม.<br>รถจักรยานยนต์: 5 บาท/กม.",
        mn_ch5_t2_r2_c1: "พนักงานฝ่ายขาย",
        mn_ch5_t2_r2_c2: "อนุมัติจากผู้อำนวยการฝ่ายขายก่อนเท่านั้น",
        mn_ch5_t2_taxi: "แท็กซี่",
        mn_ch5_t2_taxi_r: "ตามใบเสร็จ",
        mn_ch5_t2_flight: "การบิน",
        mn_ch5_t2_flight_r: "ชั้นประหยัด",
        mn_ch5_t2_tax: "ภาษีสนามบิน",
        mn_ch5_t2_tax_r: "ตามใบเสร็จ",
        mn_ch5_t2_toll: "ค่าผ่านทางและที่จอดรถ",
        mn_ch5_t2_toll_r: "ตามใบเสร็จ",
        mn_ch5_sec3_2_title: "5.3.2 เบี้ยเลี้ยง (Per Diem)",
        mn_ch5_sec3_2_l1: "ในประเทศ: <strong>270 บาท/วัน</strong> (เฉพาะพนักงานภายใน)",
        mn_ch5_sec3_2_l2: "ต่างประเทศ: <strong>500 บาท/วัน</strong> (ค่าของว่าง/เครื่องดื่ม) + ค่าอาหารตามจริง (สูงสุด 3,100)",
        mn_ch5_sec3_3_title: "5.3.3 ค่าที่พัก (Accommodation)",
        mn_ch5_sec3_3_l1: "ในประเทศ: <strong>550 บาท/คืน</strong> (หรือโรงแรมพันธมิตร)",
        mn_ch5_sec3_3_l2: "ต่างประเทศ: ตามเรทเมืองที่ไป (จองผ่านธุรการ)",
        mn_ch5_sec3_3_l3: "ห้ามชาย-หญิงพักห้องเดียวกัน",
        mn_ch5_sec4_title: "5.4 เงื่อนไขการขอเบิกค่าใช้จ่าย",
        mn_ch5_sec4_l1: "ค่าเดินทางยื่นอย่างช้าที่สุดในเดือนถัดไป",
        mn_ch5_sec4_l2: "ส่งใบขอเบิกพร้อมใบเสร็จต้นฉบับที่แผนกบัญชี <strong>ก่อนวันที่ 22 ของเดือน</strong>",
        mn_ch5_sec4_l3: "หากเกินกำหนดจะถูกนำไปจ่ายในรอบเดือนถัดไป",
        mn_ch5_sec4_l4: "บริษัทสงวนสิทธิ์ปฏิเสธการจ่ายหากไม่มีเอกสารตัวจริง",
        mn_ch5_sec5_title: "5.5 การฝึกอบรมและการพัฒนา",
        mn_ch5_sec5_l1: "สิทธิเข้าร่วมอบรมสูงสุด <strong>40 ชั่วโมงต่อปี</strong> (รวมภายใน/ภายนอก)",
        mn_ch5_sec5_l2: "พนักงานที่ยื่นใบลาออก/ถูกสอบสวน ไม่มีสิทธิอบรม",
        mn_ch5_sec5_l3: "อาจต้องลงนามใน <strong>ข้อตกลงสัญญาค้ำประกัน</strong> สำหรับการอบรมที่บริษัทคัดเลือกให้",
        mn_ch5_sec5_l4: "ต้องส่งแบบประเมินผลการอบรมให้ HR ภายใน 2 วันทำการหลังอบรมจบ",

        // Chapter 6
        mn_ch6_sec1_title: "6.1 การจ่ายเงินเดือน",
        mn_ch6_sec1_desc: "จ่ายใน <strong>วันศุกร์สุดท้ายของเดือน</strong> (หรือวันทำการสุดท้ายหากตรงกับวันหยุด)",
        mn_ch6_sec2_title: "6.2 กองทุนสำรองเลี้ยงชีพ (EPF)",
        mn_ch6_table1_h1: "อายุงาน",
        mn_ch6_table1_h2: "เงินสมทบ (บริษัท)",
        mn_ch6_table1_h3: "เงินสะสม (พนักงาน)",
        mn_ch6_t1_1: "&lt; 2 ปี",
        mn_ch6_t1_2: "2 - &lt; 5 ปี",
        mn_ch6_t1_3: "&ge; 5 ปี",
        mn_ch6_t1_c1: "สูงสุด 8%",
        mn_ch6_t1_c2: "สูงสุด 10%",
        mn_ch6_sec5_title: "6.5 การขึ้นเงินเดือนและโบนัส",
        mn_ch6_sec5_desc: "ขึ้นอยู่กับ <strong>ดุลพินิจของบริษัท</strong> และผลการปฏิบัติงานประจำปี โดยพิจารณาจาก:",
        mn_ch6_sec5_l1: "การปรับปรุงผลงาน",
        mn_ch6_sec5_l2: "ความน่าเชื่อถือและทัศนคติ",
        mn_ch6_sec5_l3: "ความร่วมมือและการปฏิบัติตามวินัย",
        mn_ch6_sec5_l4: "การประเมินผลการปฏิบัติงานประจําปี",
        mn_ch6_sec5_note: "* ไม่ถือเป็นสิทธิตามกฎหมายที่ต้องได้รับทุกปี",
        mn_ch6_sec6_title: "6.6 การทำงานล่วงเวลา (OT)",
        mn_ch6_table2_h1: "ประเภทการทำงาน",
        mn_ch6_table2_h2: "อัตราค่าตอบแทน (เงินเดือนต่อชั่วโมง)",
        mn_ch6_t2_r1_c1: "ล่วงเวลาในวันทำงานปกติ",
        mn_ch6_t2_r1_c2: "<span class='font-bold text-red-600'>1.5 เท่า</span>",
        mn_ch6_t2_r2_c1: "ทำงานในวันหยุด (เวลาปกติ)",
        mn_ch6_t2_r2_c2: "<span class='font-bold text-red-600'>1-2 เท่า</span>",
        mn_ch6_t2_r3_c1: "ล่วงเวลาในวันหยุด",
        mn_ch6_t2_r3_c2: "<span class='font-bold text-red-600'>3 เท่า</span>",
        mn_ch6_exc_title: "ข้อยกเว้น (ไม่นับเป็น OT)",
        mn_ch6_exc_l1: "ช่วงเวลาพัก",
        mn_ch6_exc_l2: "วันลาป่วย / วันพักผ่อนประจำปีและการขาดงานอื่นๆ",
        mn_ch6_exc_l3: "การเข้าร่วมฝึกอบรมในวันหยุด",
        mn_ch6_proc_title: "ขั้นตอนการเบิก",
        mn_ch6_proc_l1: "<u>ต้องได้รับอนุมัติจากหัวหน้าก่อนทำ</u>",
        mn_ch6_proc_l2: "ส่งแบบฟอร์มภายในวันที่ <strong>20 ของเดือน</strong>",

        // Chapter 7
        mn_ch7_sec1_title: "ความซื่อสัตย์",
        mn_ch7_sec1_l1: "ปฏิบัติตามกฎหมายและมาตรฐานจริยธรรมสูงสุด",
        mn_ch7_sec1_l2: "ห้ามเปิดเผยข้อมูลความลับของบริษัท/ลูกค้า",
        mn_ch7_sec1_l3: "ห้ามใช้ซอฟต์แวร์ละเมิดลิขสิทธิ์",
        mn_ch7_sec1_l4: "ต้องเคารพความเป็นส่วนตัวของผู้ใช้รายอื่นตลอดเวลา ไฟล์ แผ่นดิสก์ จดหมายอิเล็กทรอนิกส์ ข้อมูล ฯลฯ",
        mn_ch7_sec2_title: "พฤติกรรมส่วนบุคคลและจริยธรรม",
        mn_ch7_sec2_l1: "ห้ามประกอบธุรกิจแข่งขันกับบริษัท",
        mn_ch7_sec2_l2: "ห้ามรับของกำนัลที่มีมูลค่าสูงหรือสินบน",
        mn_ch7_sec2_l3: "ห้ามยืมเงินลูกค้าหรือคู่ค้า",
        mn_ch7_sec2_l4: "การอ้างชื่อบริษัท ห้ามใช้ชื่อหรือความสัมพันธ์กับบริษัทไปรับรอง/ส่งเสริมองค์กรอื่น",
        mn_ch7_sec2_l5: "การนําเข้าสู่ระบบซึ่งสิ่งลามกอนาจารหรือสิ่งที่คุกคามในพื้นที่ที่สามารถเข้าถึงได้อย่างสาธารณะ",
        mn_ch7_sec2_l6: "ต้องเชื่อฟังอย่างสุจริตและอย่างเต็มที่และปฏิบัติตามและและเคารพซึ่งกฎหมาย ฯลฯ",
        mn_ch7_it_pol: "<strong>นโยบายไอที:</strong> ห้ามใช้คอมพิวเตอร์บริษัทเพื่อธุรกิจส่วนตัว ห้ามแฮ็ก หรือละเมิดความเป็นส่วนตัวผู้อื่น",
        mn_ch7_note: "<strong>หมายเหตุ:</strong> \"เนื้อหาข้างต้นเป็นเพียงสรุปสาระสำคัญของข้อห้ามและจริยธรรมในการปฏิบัติงานเบื้องต้นเท่านั้นพนักงานมีหน้าที่ต้องศึกษาและปฏิบัติตามนโยบายบริษัทฉบับเต็มอย่างเคร่งครัดเพื่อรักษามาตรฐานขององค์กร\"",

        // Chapter 8
        mn_ch8_sec1_title: "บทลงโทษทางวินัย",
        mn_ch8_sec1_1: "1. ตักเตือนด้วยวาจา",
        mn_ch8_sec1_2: "2. ตักเตือนเป็นหนังสือ",
        mn_ch8_sec1_3: "3. พักงาน (ไม่จ่ายค่าจ้าง)",
        mn_ch8_sec1_4: "4. เลิกจ้าง",
        mn_ch8_sec2_title: "ความผิดร้ายแรง (เลิกจ้างทันที/ไม่จ่ายชดเชย)",
        mn_ch8_sec2_l1: "ทุจริต / ยักยอกเงิน / สร้างยอดขายเท็จ",
        mn_ch8_sec2_l2: "ละทิ้งหน้าที่ติดต่อกัน 3 วันทำงาน",
        mn_ch8_sec2_l3: "เสพยาเสพติด / ดื่มสุราในบริษัท / การโจรกรรม",
        mn_ch8_sec2_l4: "เปิดเผยความลับบริษัท / ปลอมเอกสาร",
        mn_ch8_sec2_l5: "การกลั่นแกล้ง / การคุกคาม / และการเลือกปฏิบัต",
        mn_ch8_sec3_title: "ความผิดทั่วไป (ตักเตือน)",
        mn_ch8_sec3_l1: "มาสาย / ขาดงานโดยไม่ลา",
        mn_ch8_sec3_l2: "ใช้เวลางานทำธุระส่วนตัว",
        mn_ch8_sec3_l3: "แต่งกายไม่สุภาพ",
        mn_ch8_sec3_l4: "การพาบุคคลภายนอกมาที่สํานักงานโดยไม่ได้รับอนุญาต",
        mn_ch8_sec4_title: "ค่าชดเชยกรณีเลิกจ้าง (ตามกฎหมาย)",
        mn_ch8_table_h1: "อายุงาน",
        mn_ch8_table_h2: "ค่าชดเชย",
        mn_ch8_t_1: "120 วัน - 1 ปี", mn_ch8_t_1_v: "30 วัน",
        mn_ch8_t_2: "1 - 3 ปี", mn_ch8_t_2_v: "90 วัน",
        mn_ch8_t_3: "3 - 6 ปี", mn_ch8_t_3_v: "180 วัน",
        mn_ch8_t_4: "6 - 10 ปี", mn_ch8_t_4_v: "240 วัน",
        mn_ch8_t_5: "10 - 20 ปี", mn_ch8_t_5_v: "300 วัน",
        mn_ch8_t_6: "20 ปีขึ้นไป", mn_ch8_t_6_v: "400 วัน",

        // Chapter 9
        mn_ch9_desc: "สำหรับพนักงานที่รู้สึกไม่ได้รับความเป็นธรรมในการปฏิบัติงาน หรือมีข้อขัดแย้ง (ไม่ใช่การขอเลื่อนตำแหน่งหรือเรื่องส่วนตัว)",
        mn_ch9_step1_title: "ขั้นตอนที่ 1: หารือหัวหน้างาน",
        mn_ch9_step1_desc: "พูดคุยกับผู้บังคับบัญชาโดยตรงหรือหัวหน้าหน่วยธุรกิจของตนก่อนเพื่อแก้ปัญหาเบื้องต้น",
        mn_ch9_step2_title: "ขั้นตอนที่ 2: ยื่นเรื่องต่อฝ่ายบริหาร",
        mn_ch9_step2_desc: "หากไม่ได้รับการแก้ไขใน <strong>3 วันทำการ</strong> ให้ยื่นหนังสือต่อ HR เพื่อขอนัดพบผู้บริหารระดับสูง (COO/CEO/MD)",
        mn_ch9_step3_title: "ขั้นตอนที่ 3: การตัดสิน",
        mn_ch9_step3_desc: "HR จะนัดหมายภายใน 7 วัน และฝ่ายบริหารจะแจ้งผลการตัดสินภายใน <strong>3 วันทำการ</strong> หลังการประชุม (ถือเป็นที่สิ้นสุด)",
        
        // Calculator Section
        calc_sub: "ตรวจสอบสิทธิตามอายุงานและนโยบายบริษัท",
        calc_date_label: "วันที่เริ่มงาน",
        calc_today: "วันนี้:",
        calc_tenure: "อายุงาน:",
        btn_calc: "คำนวณสิทธิ",
        calc_ph_title: "กรุณาระบุวันที่เริ่มงาน",
        calc_ph_desc: "ระบบจะคำนวณสิทธิวันลาตามระเบียบให้คุณอัตโนมัติ",
        calc_unit: "วัน",
        calc_desc: "สิทธิวันหยุดพักผ่อนประจำปีของคุณ",
        calc_detail_title: "รายละเอียด",
        
        // Modals & Placeholders
        login_title: "Admin Console",
        placeholder_user: "Username",
        placeholder_pass: "Password",
        btn_login: "เข้าสู่ระบบ",
        new_post_title: "เพิ่มประกาศใหม่",
        post_topic_label: "หัวข้อประกาศ",
        placeholder_topic: "ใส่หัวข้อเรื่อง...",
        post_content_label: "เนื้อหา",
        btn_post: "โพสต์ประกาศ",
        change_pass_title: "เปลี่ยนรหัสผ่าน Admin",
        new_user_label: "Username ใหม่:",
        new_pass_label: "Password ใหม่:",
        btn_save_pass: "บันทึกรหัสผ่านใหม่",
        
        // Dynamic JS Strings
        pin_badge: "ปักหมุด",
        hidden_admin: "ซ่อนอยู่ (Admin เห็นเท่านั้น)",
        pin: "ปักหมุด",
        unpin: "เลิกปักหมุด",
        edit: "แก้ไข",
        show: "แสดง",
        hide: "ซ่อน",
        delete: "ลบ",
        btn_saving: "กำลังบันทึก...",
        btn_save_edit: "บันทึกการแก้ไข",
        alert_no_topic: "กรุณาใส่หัวข้อ",
        confirm_delete: "ต้องการลบประกาศนี้ใช่หรือไม่?",
        alert_error: "เกิดข้อผิดพลาด: ",
        alert_fill_all: "กรุณากรอกข้อมูลให้ครบถ้วน",
        btn_checking: "กำลังตรวจสอบ...",
        alert_login_fail: "Username หรือ Password ไม่ถูกต้อง",
        confirm_pass: "คุณแน่ใจหรือไม่ว่าจะเปลี่ยนรหัสผ่านแอดมิน?",
        alert_pass_success: "เปลี่ยนรหัสผ่านสำเร็จ!",
        calc_invalid_date_badge: "วันที่ไม่ถูกต้อง",
        calc_invalid_date_msg: "<span class='text-red-600 font-bold'>ไม่สามารถเลือกวันที่ในอนาคตได้</span><br>กรุณาเลือกวันที่เริ่มงานใหม่อีกครั้ง",
        calc_probation_badge: "ช่วงทดลองงาน (Probation)",
        calc_probation_msg: "อายุงานของคุณคือ {days} วัน <br> ตามระเบียบบริษัท พนักงานจะได้รับสิทธิวันหยุดพักผ่อนประจำปีหลังจากผ่านช่วงทดลองงาน (119 วัน) แล้วเท่านั้น",
        calc_prorate_badge: "อายุงานไม่ถึง 1 ปี (Pro-rate)",
        calc_prorate_msg: "ผ่านช่วงทดลองงานแล้ว (อายุงาน {days} วัน) <br> ได้รับสิทธิตามสัดส่วนจากฐาน 14 วัน <br><br> สูตร: ({days} / 365) × 14 = {raw} วัน",
        calc_1_2_badge: "อายุงาน 1 - < 2 ปี",
        calc_1_2_msg: "คุณได้รับสิทธิวันหยุดพักผ่อนประจำปีตามปกติ 14 วัน เนื่องจากมีอายุงานครบ 1 ปีขึ้นไป",
        calc_2_5_badge: "อายุงาน 2 - < 5 ปี",
        calc_2_5_msg: "คุณได้รับสิทธิวันหยุดพักผ่อนประจำปีเพิ่มขึ้นเป็น 17 วัน ตามอายุงาน",
        calc_5_up_badge: "อายุงาน 5 ปีขึ้นไป",
        calc_5_up_msg: "คุณได้รับสิทธิวันหยุดพักผ่อนประจำปีสูงสุด 19 วัน ตามอายุงาน"
    }
};

// ฟังก์ชันดึงคำแปลไปใช้ใน Javascript (รองรับการส่งตัวแปร {param})
function t(key, params = {}) {
    // บังคับภาษาเริ่มต้นเป็น 'th' ตลอด หากยังไม่มีในระบบ (ไม่พึ่งพาภาษาอังกฤษแล้ว)
    let lang = localStorage.getItem('wurth_lang') || 'th';
    let str = (translations[lang] && translations[lang][key]) ? translations[lang][key] : key;
    for (let k in params) {
        str = str.replace(`{${k}}`, params[k]);
    }
    return str;
}

// ฟังก์ชันสำหรับตั้งค่าภาษาใหม่
function setLanguage(lang) {
    localStorage.setItem('wurth_lang', lang);
    
    // อัปเดตข้อความบนปุ่มเลือกภาษา
    const btnText = document.getElementById('current-lang-text');
    if (btnText) {
        btnText.innerText = lang === 'en' ? 'English' : 'ไทย';
    }

    // ทำการเปลี่ยน Text ตาม attribute 'data-i18n' (รองรับ Tag HTML ด้านใน)
    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            el.innerHTML = translations[lang][key];
        }
    });

    // ทำการเปลี่ยน Placeholder ใน Input
    const placeholders = document.querySelectorAll('[data-i18n-placeholder]');
    placeholders.forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (translations[lang] && translations[lang][key]) {
            el.placeholder = translations[lang][key];
        }
    });

    // สั่งให้เครื่องคิดเลขคำนวณและดึงข้อความใหม่มาแสดง (ถ้ากรอกวันไปแล้ว)
    if(typeof calculateLeave === 'function' && document.getElementById('start-date').value) {
        calculateLeave();
    }
    
    // โหลดโพสต์ใหม่เพื่อให้ปุ่มเครื่องมือแอดมินและป้ายกำกับเปลี่ยนภาษา
    if(typeof renderPosts === 'function' && window.currentPostsData) {
        renderPosts(window.currentPostsData);
    }

    // ปิดเมนูภาษาหลังจากเลือกเสร็จ
    const langMenu = document.getElementById('lang-menu');
    if(langMenu) langMenu.classList.add('hidden');
    
    // Render icon ใหม่เผื่อโดน innerHTML ทับ
    if (typeof lucide !== 'undefined') lucide.createIcons();
}

// ตรวจสอบภาษาตอนโหลดหน้าเว็บ โดยบังคับให้ระบบยึดค่าเริ่มต้นเป็นภาษาไทยอย่างสมบูรณ์
document.addEventListener('DOMContentLoaded', () => {
    let savedLang = localStorage.getItem('wurth_lang');
    // หากไม่มีการเลือกภาษามาก่อนเลย ให้เซ็ตค่า Default เป็นไทยทับไปเลย
    if (!savedLang) {
        savedLang = 'th';
        localStorage.setItem('wurth_lang', 'th');
    }
    setLanguage(savedLang);
});
